// mod print;
// mod vars;
// mod types;
// mod strings;
// mod tuples;
// mod arrays;
// mod vectors;
// mod conditionals;
// mod loops;
// mod functions;
// mod pointer_ref;
// mod structs;
// mod enums;
// mod cli;
// mod option;
// mod iterators;
// mod concurrency;
// mod point; 
// mod formatting;
// mod matrix_tuple;
// mod structs_rbe;
// mod enums_use;
// mod enums_clike;
// mod linked_list;
// mod from_trait;
// mod to_string_trait;
// mod from_str_trait;
// mod nesting_and_loops;
mod returning_from_loop;

fn main() {
    // print::run();
    // vars::run();
    // types::run();
    // strings::run();
    // tuples::run();
    // arrays::run();
    // vectors::run();
    // conditionals::run();
    // loops::run();
    // functions::run();
    // pointer_ref::run();
    // structs::run();
    // enums::run();
    // cli::run();
    // option::run();
    // iterators::run();
    // concurrency::run();
    // point::run();
    // formatting::run();
    // matrix_tuple::run();
    // structs_rbe::run();
    // enums_use::run();
    // enums_clike::run();
    // linked_list::run();
    // from_trait::run();
    // to_string_trait::run();
    // from_str_trait::run();
    // nesting_and_loops::run();
    returning_from_loop::run();
}
